import React from "react";

import '../../../css/industry-css.css';

import {
    BrowserRouter as Router,
    Switch,
    Route,
    Link
} from "react-router-dom";

import GetStarted from '../../../components/home-component/get-started';

import { Helmet } from "react-helmet";


const ComplianceProcess = () => {

    return (
        <>
            <div className="application">
                <Helmet>
                    <html lang="en" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <title>RPA improves compliance process | Featsystems</title>
                    <meta name="description" content="Featsystems have an RPA solution that can manage, log, and track the company&#39;s compliance regulatory aspects." />

                    <meta name="keywords" />
                    <meta property="og:title" content="RPA improves compliance process | Featsystems" />
                    <meta property="og:image" content="https://www.featsystems.com/content/images/og_img/Compliances-og.jpg" />
                    <meta property="og:description" content="Featsystems have an RPA solution that can manage, log, and track the company&#39;s compliance regulatory aspects." />
                    <meta property="og:url" content="https://www.featsystems.com/compliance" />

                    <link rel="canonical" href="https://www.featsystems.com/compliance" />
                </Helmet>
            </div>
            <section className="client-section bg-vector">
                <div className="container">
                    <div className="row align-center column-reverse">
                        <div className="col-lg-12 text-center">
                            <div className="cl-text">
                                <h2 className="h1 mt-0">Compliance process in finance & banking</h2>


                            </div>
                            <div className="gt-button mt-40">
                                <Link to="/contact" className="btn btn-dark">Get Started</Link>
                            </div>
                        </div>

                    </div>
                </div>
            </section>
            <section className="breadcrumb-section">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-12">
                            <ul className="breadcrumb">
                                <li><Link to="/home">Home</Link></li>
                                <li><Link to="/automation-solutions">By Industry</Link></li>
                                <li><Link to="/rpa-finance-and-banking">Finance & Banking</Link></li>
                                <li>Compliance</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </section>





            <section className="ind-section">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-12">
                            <h2 className="h2 mb-50 text-center">Using RPA Compliance process can be improved</h2>
                            <div className="cl-text">
                                <ul>
                                    <li>With so much money involved, every Banking organization has to strictly adhere to compliance for the smooth functioning of everyday transactions. With a report generated by Accenture, 73% of the compliance officers trusted Automation tools to improve Compliance activities in the next three years.</li>
                                    <li>With RPA Solutions, compliance can be maintained 24*7 with no compromise on accuracy and quality. RPA tools can collect transactional information and analyze the quality of such transactions referring to some pre-defined validation rules, a typical use case for RPA implementation. If any transaction raises suspicion, it can be immediately brought to notice with the concerned person saving Banks from reputational damage.</li>
                                    <li>In another survey, it was quite evident that 85% of the people reported RPA bots meeting or exceeding their expectations when it comes to Accuracy, Flexibility, and Compliance. Hence, RPA Implementation in the compliance process of any financial institution can be considered as a very good strategic investment.</li>
                                </ul>
                            </div>
                        </div>


                    </div>
                </div>
            </section>



            <section className="solution-section">
                <div className="container">
                    <div className="sl_section pd-30">
                        <div className="sl_head"><h2>Our Finance &amp; Banking Solutions</h2></div>
                        <div className="sl_boxes">
                            <Link to="/account-opening-process">Account Opening process</Link>
                            <Link to="/customer-service">Customer Service</Link>
                            <Link to="/ekyc-process">KYC process</Link>
                            <Link to="/report-automation">Report Automation</Link>
                            <Link to="/account-closure-process">Account Closure Process</Link>
                            <Link to="/mf-reconciliation-process">MF Reconciliation Process</Link>
                            <Link to="/accounts-payable">Accounts Payable</Link>
                            <Link to="/general-ledger">General Ledger</Link>
                            <Link to="/credit-card-processing">Credit card processing</Link>
                            <Link to="/mortgage-processing">Mortgage processing</Link>
                            <Link to="/fraud-detection">Fraud Detection</Link>
                        </div>
                    </div>
                </div>
            </section>




            <GetStarted />

        </>
    );
};

export default ComplianceProcess;